### ISSUE TITLE
Homepage - Our Projects: enhance the arrow navigator in smaller resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/QSM-Fabrication#12]
![image](https://cloud.githubusercontent.com/assets/17717843/14698971/5575e300-07c6-11e6-9fd6-66ffcc14ed7a.png)

**Comment by joancapuyan** [comment]
The navigation arrows are removed. https://github.com/titan-cebu/QSM-Fabrication/issues/40
